CREATE TABLE master_data (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Type VARCHAR(100),
    Category VARCHAR(200),
    Country VARCHAR(100),
    State VARCHAR(200),
    District VARCHAR(200),
    Area VARCHAR(200),
    Name VARCHAR(500),
    Address TEXT,
    Phone VARCHAR(100),
    Website TEXT,
    `Company Scale` VARCHAR(100),
    Reach VARCHAR(100),
    `Key Pax` VARCHAR(200),
    `Phone 1` VARCHAR(100),
    `Phone 2` VARCHAR(100),
    `Phone 3` VARCHAR(100),
    `Phone 4` VARCHAR(100),
    `Phone 5` VARCHAR(100),
    Email VARCHAR(300),
    Product TEXT,
    `Created At` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);